export { default as Sidebar } from "./sidebar"
export { default as Navbar } from "./navbar"
export { default as Numbers } from "./numbers"
export { default as CreateLifeContract } from "./createLife"
export { default as LifeList } from "./lifeList"
export { default as UpdateLifeContract } from "./updateLife"
